;
; AssemblerDA2BT1.asm
;
; Created: 3/4/2019 3:13:20 PM
; Author : Home
;


	.ORG 0
	JMP 	MAIN

.ORG 0X02
	JMP 	EX0_ISR
	
MAIN: 
	LDI 	R20, HIGH(RAMEND)
	OUT 	SPH, R20
	LDI 	R20, LOW(RAMEND)
	OUT 	SPL, R20 			; INITIALIZE STACK
	LDI 	R20, 0X02 			; FALLING EDGE TRIGGERED 
	STS		EICRA, R20 			; EXTERNAL INTERRUPT CONTROL REG AIS SET
	SBI 	DDRB, 5 			; OUTPUT PORTB.5
	CBI		PORTB, 5
	SBI 	PORTD, 2 			; PULL-UP RESISTOR IS ACTIVATED
	LDI 	R20, 1<<INT0 		; TURN ON INT0 
	OUT 	EIMSK, R20 			; EXTERNAL INTERRUPT MASK REGISTER
	SEI 						; TURN ON INTERRUPTS
HERE: JMP HERE
EX0_ISR:
	SBI		PORTB, 5
	RCALL	YALED
	CBI		PORTB, 5	
	RETI
YALED:
LDI R20, 44
D0: LDI R21, 200
D1: LDI R22, 250
D2:  NOP
NOP
DEC R22
BRNE D2
DEC R21
BRNE D1
DEC R20
BRNE D0
	RET